name: Build Docker Images

on:
  repository_dispatch:
    types: [build-lambda-images]

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    name: Step 2 - Build Writer & Reader Docker Images

    steps:
      - uses: actions/checkout@v3

      - name: Build and Push Writer Image
        run: echo "Build image and Trigger Repo A to deploy infra"

      - name: Trigger Infra Deploy (Repo A)
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}  # ✅ Correct usage
          repository: makgopajm/repoA
          event-type: deploy-infra
