name: Build Docker Images

on:
  repository_dispatch:
    types: [build-lambda-images]

env:
 token:  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

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    name: Step 2 - Build Writer & Reader Docker Images

    steps:
      - uses: actions/checkout@v3

      - name: Build and Push Writer Image
        run:  echo "Build image and Trigger Repo A to deploy infa"


      - name: Trigger Infra Deploy (Repo A)
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ env.token }}
          repository: makgopajm/repoA
          event-type: deploy-infra
